Given the dataset attached in the folder:

a)       For each team, what difference in ‘rest’ can you see, when playing ‘home’ games, v/s when playing ‘away’ games?

 

b)      What is the effect that ‘rest’ has, on overall match-outcome?

 

c)       When are teams more victorious- when playing at home, or when playing away?

In [74]:
import pandas as pd
from datetime import datetime

In [3]:
#Loading the dataframes
df_october = pd.read_csv('./data/October.csv')
df_november = pd.read_csv('./data/November.csv')
df_december = pd.read_csv('./data/December.csv')

----------------------------------------

- Displaying the 3 datasets to check they were properly load

In [4]:
df_december

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,Tue Dec 1 2015,7:00p,Washington Wizards,97,Cleveland Cavaliers,85,Box Score,NaN,20562,Quicken Loans Arena,NaN
1,Tue Dec 1 2015,7:00p,Los Angeles Lakers,91,Philadelphia 76ers,103,Box Score,NaN,20510,Wells Fargo Center,NaN
2,Tue Dec 1 2015,7:30p,Phoenix Suns,91,Brooklyn Nets,94,Box Score,NaN,12787,Barclays Center,NaN
3,Tue Dec 1 2015,8:00p,Orlando Magic,96,Minnesota Timberwolves,93,Box Score,NaN,10694,Target Center,NaN
4,Tue Dec 1 2015,8:00p,Memphis Grizzlies,113,New Orleans Pelicans,104,Box Score,NaN,16020,Smoothie King Center,NaN
...,...,...,...,...,...,...,...,...,...,...,...
223,Thu Dec 31 2015,6:00p,Milwaukee Bucks,120,Indiana Pacers,116,Box Score,NaN,16348,Bankers Life Fieldhouse,NaN
224,Thu Dec 31 2015,7:00p,Golden State Warriors,114,Houston Rockets,110,Box Score,NaN,18313,Toyota Center,NaN
225,Thu Dec 31 2015,8:00p,Los Angeles Clippers,95,New Orleans Pelicans,89,Box Score,NaN,16920,Smoothie King Center,NaN
226,Thu Dec 31 2015,8:00p,Phoenix Suns,106,Oklahoma City Thunder,110,Box Score,NaN,18203,Chesapeake Energy Arena,NaN
227,Thu Dec 31 2015,9:00p,Portland Trail Blazers,96,Utah Jazz,109,Box Score,NaN,19380,Vivint Smart Home Arena,NaN

In [5]:
df_november

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,Sun Nov 1 2015,2:00p,Atlanta Hawks,94,Charlotte Hornets,92,Box Score,NaN,18691,Time Warner Cable Arena,NaN
1,Sun Nov 1 2015,3:30p,San Antonio Spurs,95,Boston Celtics,87,Box Score,NaN,17461,TD Garden,NaN
2,Sun Nov 1 2015,6:00p,Houston Rockets,89,Miami Heat,109,Box Score,NaN,19600,AmericanAirlines Arena,NaN
3,Sun Nov 1 2015,6:00p,Milwaukee Bucks,87,Toronto Raptors,106,Box Score,NaN,19800,Air Canada Centre,NaN
4,Sun Nov 1 2015,7:00p,Orlando Magic,87,Chicago Bulls,92,Box Score,NaN,21585,United Center,NaN
...,...,...,...,...,...,...,...,...,...,...,...
218,Mon Nov 30 2015,8:00p,San Antonio Spurs,89,Chicago Bulls,92,Box Score,NaN,21909,United Center,NaN
219,Mon Nov 30 2015,8:00p,Denver Nuggets,74,Milwaukee Bucks,92,Box Score,NaN,10187,BMO Harris Bradley Center,NaN
220,Mon Nov 30 2015,9:00p,Golden State Warriors,106,Utah Jazz,103,Box Score,NaN,19911,Vivint Smart Home Arena,NaN
221,Mon Nov 30 2015,10:00p,Dallas Mavericks,98,Sacramento Kings,112,Box Score,NaN,16937,Sleep Train Arena,NaN
222,Mon Nov 30 2015,10:30p,Portland Trail Blazers,87,Los Angeles Clippers,102,Box Score,NaN,19060,STAPLES Center,NaN

In [6]:
df_october

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,Tue Oct 27 2015,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,United Center,NaN
1,Tue Oct 27 2015,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,Philips Arena,NaN
2,Tue Oct 27 2015,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,Oracle Arena,NaN
3,Wed Oct 28 2015,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,Amway Center,NaN
4,Wed Oct 28 2015,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,TD Garden,NaN
5,Wed Oct 28 2015,7:30p,Chicago Bulls,115,Brooklyn Nets,100,Box Score,NaN,17732,Barclays Center,NaN
6,Wed Oct 28 2015,7:30p,Utah Jazz,87,Detroit Pistons,92,Box Score,NaN,18434,The Palace of Auburn Hills,NaN
7,Wed Oct 28 2015,7:30p,Indiana Pacers,99,Toronto Raptors,106,Box Score,NaN,19800,Air Canada Centre,NaN
8,Wed Oct 28 2015,7:30p,Charlotte Hornets,94,Miami Heat,104,Box Score,NaN,19724,AmericanAirlines Arena,NaN
9,Wed Oct 28 2015,8:00p,New York Knicks,122,Milwaukee Bucks,97,Box Score,NaN,18717,BMO Harris Bradley Center,NaN
10,Wed Oct 28 2015,8:00p,San Antonio Spurs,106,Oklahoma City Thunder,112,Box Score,NaN,18203,Chesapeake Energy Arena,NaN
11,Wed Oct 28 2015,8:00p,Cleveland Cavaliers,106,Memphis Grizzlies,76,Box Score,NaN,18119,FedEx Forum,NaN
12,Wed Oct 28 2015,8:00p,Denver Nuggets,105,Houston Rockets,85,Box Score,NaN,18240,Toyota Center,NaN
13,Wed Oct 28 2015,10:00p,Dallas Mavericks,111,Phoenix Suns,95,Box Score,NaN,18055,Talking Stick Resort Arena,NaN
14,Wed Oct 28 2015,10:00p,New Orleans Pelicans,94,Portland Trail Blazers,112,Box Score,NaN,19393,Moda Center,NaN
15,Wed Oct 28 2015,10:00p,Los Angeles Clippers,111,Sacramento Kings,104,Box Score,NaN,17458,Sleep Train Arena,NaN
16,Wed Oct 28 2015,10:30p,Minnesota Timberwolves,112,Los Angeles Lakers,111,Box Score,NaN,18997,STAPLES Center,NaN
17,Thu Oct 29 2015,7:00p,Memphis Grizzlies,112,Indiana Pacers,103,Box Score,NaN,18165,Bankers Life Fieldhouse,NaN
18,Thu Oct 29 2015,8:00p,Atlanta Hawks,112,New York Knicks,101,Box Score,NaN,19812,Madison Square Garden (IV),NaN
19,Thu Oct 29 2015,10:30p,Dallas Mavericks,88,Los Angeles Clippers,104,Box Score,NaN,19218,STAPLES Center,NaN
20,Fri Oct 30 2015,7:00p,Miami Heat,92,Cleveland Cavaliers,102,Box Score,NaN,20562,Quicken Loans Arena,NaN
21,Fri Oct 30 2015,7:00p,Utah Jazz,99,Philadelphia 76ers,71,Box Score,NaN,17122,Wells Fargo Center,NaN
22,Fri Oct 30 2015,7:00p,Oklahoma City Thunder,139,Orlando Magic,136,Box Score,2OT,18846,Amway Center,NaN
23,Fri Oct 30 2015,7:30p,Toronto Raptors,113,Boston Celtics,103,Box Score,NaN,16898,TD Garden,NaN
24,Fri Oct 30 2015,7:30p,Chicago Bulls,94,Detroit Pistons,98,Box Score,OT,16035,The Palace of Auburn Hills,NaN
25,Fri Oct 30 2015,8:00p,Charlotte Hornets,94,Atlanta Hawks,97,Box Score,NaN,17024,Philips Arena,NaN
26,Fri Oct 30 2015,8:00p,Washington Wizards,118,Milwaukee Bucks,113,Box Score,NaN,13858,BMO Harris Bradley Center,NaN
27,Fri Oct 30 2015,8:30p,Brooklyn Nets,75,San Antonio Spurs,102,Box Score,NaN,18418,AT&T Center,NaN
28,Fri Oct 30 2015,9:00p,Minnesota Timberwolves,95,Denver Nuggets,78,Box Score,NaN,17660,Pepsi Center,NaN
29,Fri Oct 30 2015,9:30p,Golden State Warriors,112,Houston Rockets,92,Box Score,NaN,18142,Toyota Center,NaN
30,Fri Oct 30 2015,10:00p,Los Angeles Lakers,114,Sacramento Kings,132,Box Score,NaN,17391,Sleep Train Arena,NaN
31,Fri Oct 30 2015,10:30p,Portland Trail Blazers,92,Phoenix Suns,110,Box Score,NaN,18055,Talking Stick Resort Arena,NaN
32,Sat Oct 31 2015,7:00p,Utah Jazz,97,Indiana Pacers,76,Box Score,NaN,14412,Bankers Life Fieldhouse,NaN
33,Sat Oct 31 2015,7:00p,New York Knicks,117,Washington Wizards,110,Box Score,NaN,20356,Verizon Center,NaN
34,Sat Oct 31 2015,7:30p,Golden State Warriors,134,New Orleans Pelicans,120,Box Score,NaN,18406,Smoothie King Center,NaN
35,Sat Oct 31 2015,8:00p,Brooklyn Nets,91,Memphis Grizzlies,101,Box Score,NaN,16013,FedEx Forum,NaN
36,Sat Oct 31 2015,10:00p,Phoenix Suns,101,Portland Trail Blazers,90,Box Score,NaN,17906,Moda Center,NaN
37,Sat Oct 31 2015,10:30p,Sacramento Kings,109,Los Angeles Clippers,114,Box Score,NaN,19060,STAPLES Center,NaN

In [14]:
print(df_october.columns)
print(df_november.columns)
print(df_december.columns)

Index(['Date', 'Start (ET)', 'Visitor/Neutral', 'PTS', 'Home/Neutral', 'PTS.1',
       'Unnamed: 6', 'Unnamed: 7', 'Attend.', 'Arena', 'Notes'],
      dtype='object')
Index(['Date', 'Start (ET)', 'Visitor/Neutral', 'PTS', 'Home/Neutral', 'PTS.1',
       'Unnamed: 6', 'Unnamed: 7', 'Attend.', 'Arena', 'Notes'],
      dtype='object')
Index(['Date', 'Start (ET)', 'Visitor/Neutral', 'PTS', 'Home/Neutral', 'PTS.1',
       'Unnamed: 6', 'Unnamed: 7', 'Attend.', 'Arena', 'Notes'],
      dtype='object')

------------------------------------------

- Concatenating the three dataset since they all have the same features and will be better for the analysis

In [16]:
frames = [df_december, df_november, df_october]
df = pd.concat(frames)

In [71]:
df

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,Tue Dec 1 2015,7:00p,Washington Wizards,97,Cleveland Cavaliers,85,Box Score,NaN,20562,Quicken Loans Arena,NaN
1,Tue Dec 1 2015,7:00p,Los Angeles Lakers,91,Philadelphia 76ers,103,Box Score,NaN,20510,Wells Fargo Center,NaN
2,Tue Dec 1 2015,7:30p,Phoenix Suns,91,Brooklyn Nets,94,Box Score,NaN,12787,Barclays Center,NaN
3,Tue Dec 1 2015,8:00p,Orlando Magic,96,Minnesota Timberwolves,93,Box Score,NaN,10694,Target Center,NaN
4,Tue Dec 1 2015,8:00p,Memphis Grizzlies,113,New Orleans Pelicans,104,Box Score,NaN,16020,Smoothie King Center,NaN
...,...,...,...,...,...,...,...,...,...,...,...
33,Sat Oct 31 2015,7:00p,New York Knicks,117,Washington Wizards,110,Box Score,NaN,20356,Verizon Center,NaN
34,Sat Oct 31 2015,7:30p,Golden State Warriors,134,New Orleans Pelicans,120,Box Score,NaN,18406,Smoothie King Center,NaN
35,Sat Oct 31 2015,8:00p,Brooklyn Nets,91,Memphis Grizzlies,101,Box Score,NaN,16013,FedEx Forum,NaN
36,Sat Oct 31 2015,10:00p,Phoenix Suns,101,Portland Trail Blazers,90,Box Score,NaN,17906,Moda Center,NaN
37,Sat Oct 31 2015,10:30p,Sacramento Kings,109,Los Angeles Clippers,114,Box Score,NaN,19060,STAPLES Center,NaN

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 489 entries, 0 to 37
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             489 non-null    object
 1   Start (ET)       489 non-null    object
 2   Visitor/Neutral  489 non-null    object
 3   PTS              489 non-null    int64
 4   Home/Neutral     489 non-null    object
 5   PTS.1            489 non-null    int64
 6   Unnamed: 6       489 non-null    object
 7   Unnamed: 7       25 non-null     object
 8   Attend.          489 non-null    int64
 9   Arena            489 non-null    object
 10  Notes            1 non-null      object
dtypes: int64(3), object(8)
memory usage: 62.0+ KB

In [18]:
#Checking for all the null values in the new dataset
df.isnull().sum()

Date                 0
Start (ET)           0
Visitor/Neutral      0
PTS                  0
Home/Neutral         0
PTS.1                0
Unnamed: 6           0
Unnamed: 7         464
Attend.              0
Arena                0
Notes              488
dtype: int64

In [23]:
df['Unnamed: 7'].unique()

array([nan, 'OT', '2OT', '4OT'], dtype=object)

- Unnamed: 7 respresents if the match had any Over Time (OT)

In [25]:
df['Notes'].unique()

array([nan, 'at Mexico City Mexico'], dtype=object)

- If the match was played in any location different from nba registered stadium 'Note' indicates in which city it was played

-------------------------------

In [30]:
# array of the name of every team in the nba
Teams = df['Visitor/Neutral'].unique()
len(Teams) # number of teams in the nba

30

In [63]:
#Empty dictionaries to save the results for each team
home_wins = {}
away_wins = {}
home_matches = {}
away_matches = {}

for index, row in df.iterrows():
    home_team = row['Home/Neutral']
    away_team = row['Visitor/Neutral']
    home_points = row['PTS.1']
    away_points = row['PTS']
    
#I'm not considering a case where both teams have the same points because in basketball is not possible to draw in a match
    if home_points > away_points:
        winner = home_team
        loser = away_team
    else:
        winner = away_team
        loser = home_team

    if home_team not in home_wins:
        home_wins[home_team] = 0
        home_matches[home_team] = 0
        
    if away_team not in away_wins: 
        away_wins[away_team] = 0
        away_matches[away_team] = 0

    home_matches[home_team] += 1
    away_matches[away_team] += 1

    if winner != 'Tie':
        if winner == home_team:
            home_wins[home_team] += 1
        else:
            away_wins[away_team] += 1

In [64]:
home_wins

{'Cleveland Cavaliers': 13,
 'Philadelphia 76ers': 1,
 'Brooklyn Nets': 6,
 'Minnesota Timberwolves': 5,
 'New Orleans Pelicans': 7,
 'Portland Trail Blazers': 8,
 'Charlotte Hornets': 13,
 'Washington Wizards': 7,
 'Detroit Pistons': 11,
 'New York Knicks': 8,
 'Atlanta Hawks': 12,
 'Chicago Bulls': 13,
 'Houston Rockets': 10,
 'San Antonio Spurs': 19,
 'Los Angeles Clippers': 10,
 'Miami Heat': 13,
 'Toronto Raptors': 10,
 'Utah Jazz': 9,
 'Memphis Grizzlies': 11,
 'Sacramento Kings': 8,
 'Dallas Mavericks': 10,
 'Milwaukee Bucks': 9,
 'Oklahoma City Thunder': 16,
 'Indiana Pacers': 11,
 'Denver Nuggets': 5,
 'Boston Celtics': 9,
 'Phoenix Suns': 8,
 'Orlando Magic': 12,
 'Los Angeles Lakers': 2,
 'Golden State Warriors': 15}

In [65]:
away_wins

{'Washington Wizards': 7,
 'Los Angeles Lakers': 4,
 'Phoenix Suns': 4,
 'Orlando Magic': 7,
 'Memphis Grizzlies': 7,
 'Dallas Mavericks': 9,
 'Golden State Warriors': 15,
 'Philadelphia 76ers': 2,
 'Toronto Raptors': 10,
 'Denver Nuggets': 7,
 'New Orleans Pelicans': 3,
 'Milwaukee Bucks': 4,
 'Indiana Pacers': 7,
 'Oklahoma City Thunder': 7,
 'San Antonio Spurs': 9,
 'Boston Celtics': 9,
 'Brooklyn Nets': 3,
 'Houston Rockets': 6,
 'Cleveland Cavaliers': 8,
 'Charlotte Hornets': 4,
 'Sacramento Kings': 4,
 'Portland Trail Blazers': 6,
 'New York Knicks': 7,
 'Detroit Pistons': 7,
 'Los Angeles Clippers': 11,
 'Utah Jazz': 5,
 'Chicago Bulls': 5,
 'Miami Heat': 5,
 'Atlanta Hawks': 9,
 'Minnesota Timberwolves': 7}

In [66]:
home_matches

{'Cleveland Cavaliers': 14,
 'Philadelphia 76ers': 13,
 'Brooklyn Nets': 16,
 'Minnesota Timberwolves': 17,
 'New Orleans Pelicans': 14,
 'Portland Trail Blazers': 14,
 'Charlotte Hornets': 19,
 'Washington Wizards': 15,
 'Detroit Pistons': 16,
 'New York Knicks': 16,
 'Atlanta Hawks': 18,
 'Chicago Bulls': 18,
 'Houston Rockets': 19,
 'San Antonio Spurs': 19,
 'Los Angeles Clippers': 16,
 'Miami Heat': 20,
 'Toronto Raptors': 15,
 'Utah Jazz': 16,
 'Memphis Grizzlies': 17,
 'Sacramento Kings': 17,
 'Dallas Mavericks': 15,
 'Milwaukee Bucks': 15,
 'Oklahoma City Thunder': 20,
 'Indiana Pacers': 16,
 'Denver Nuggets': 15,
 'Boston Celtics': 17,
 'Phoenix Suns': 18,
 'Orlando Magic': 18,
 'Los Angeles Lakers': 11,
 'Golden State Warriors': 15}

In [67]:
away_matches

{'Washington Wizards': 15,
 'Los Angeles Lakers': 22,
 'Phoenix Suns': 17,
 'Orlando Magic': 14,
 'Memphis Grizzlies': 17,
 'Dallas Mavericks': 17,
 'Golden State Warriors': 17,
 'Philadelphia 76ers': 21,
 'Toronto Raptors': 18,
 'Denver Nuggets': 18,
 'New Orleans Pelicans': 18,
 'Milwaukee Bucks': 19,
 'Indiana Pacers': 16,
 'Oklahoma City Thunder': 13,
 'San Antonio Spurs': 15,
 'Boston Celtics': 15,
 'Brooklyn Nets': 16,
 'Houston Rockets': 15,
 'Cleveland Cavaliers': 16,
 'Charlotte Hornets': 12,
 'Sacramento Kings': 15,
 'Portland Trail Blazers': 21,
 'New York Knicks': 17,
 'Detroit Pistons': 17,
 'Los Angeles Clippers': 18,
 'Utah Jazz': 15,
 'Chicago Bulls': 12,
 'Miami Heat': 11,
 'Atlanta Hawks': 16,
 'Minnesota Timberwolves': 16}

In [68]:
#Winrates for each team
home_win_rates = {team : home_wins[team]/home_matches[team] for team in home_wins}
away_win_rates = {team : away_wins[team]/away_matches[team] for team in away_wins}

In [69]:
home_win_rates

{'Cleveland Cavaliers': 0.9285714285714286,
 'Philadelphia 76ers': 0.07692307692307693,
 'Brooklyn Nets': 0.375,
 'Minnesota Timberwolves': 0.29411764705882354,
 'New Orleans Pelicans': 0.5,
 'Portland Trail Blazers': 0.5714285714285714,
 'Charlotte Hornets': 0.6842105263157895,
 'Washington Wizards': 0.4666666666666667,
 'Detroit Pistons': 0.6875,
 'New York Knicks': 0.5,
 'Atlanta Hawks': 0.6666666666666666,
 'Chicago Bulls': 0.7222222222222222,
 'Houston Rockets': 0.5263157894736842,
 'San Antonio Spurs': 1.0,
 'Los Angeles Clippers': 0.625,
 'Miami Heat': 0.65,
 'Toronto Raptors': 0.6666666666666666,
 'Utah Jazz': 0.5625,
 'Memphis Grizzlies': 0.6470588235294118,
 'Sacramento Kings': 0.47058823529411764,
 'Dallas Mavericks': 0.6666666666666666,
 'Milwaukee Bucks': 0.6,
 'Oklahoma City Thunder': 0.8,
 'Indiana Pacers': 0.6875,
 'Denver Nuggets': 0.3333333333333333,
 'Boston Celtics': 0.5294117647058824,
 'Phoenix Suns': 0.4444444444444444,
 'Orlando Magic': 0.6666666666666666,
 'Los Angeles Lakers': 0.18181818181818182,
 'Golden State Warriors': 1.0}

In [72]:
away_win_rates

{'Washington Wizards': 0.4666666666666667,
 'Los Angeles Lakers': 0.18181818181818182,
 'Phoenix Suns': 0.23529411764705882,
 'Orlando Magic': 0.5,
 'Memphis Grizzlies': 0.4117647058823529,
 'Dallas Mavericks': 0.5294117647058824,
 'Golden State Warriors': 0.8823529411764706,
 'Philadelphia 76ers': 0.09523809523809523,
 'Toronto Raptors': 0.5555555555555556,
 'Denver Nuggets': 0.3888888888888889,
 'New Orleans Pelicans': 0.16666666666666666,
 'Milwaukee Bucks': 0.21052631578947367,
 'Indiana Pacers': 0.4375,
 'Oklahoma City Thunder': 0.5384615384615384,
 'San Antonio Spurs': 0.6,
 'Boston Celtics': 0.6,
 'Brooklyn Nets': 0.1875,
 'Houston Rockets': 0.4,
 'Cleveland Cavaliers': 0.5,
 'Charlotte Hornets': 0.3333333333333333,
 'Sacramento Kings': 0.26666666666666666,
 'Portland Trail Blazers': 0.2857142857142857,
 'New York Knicks': 0.4117647058823529,
 'Detroit Pistons': 0.4117647058823529,
 'Los Angeles Clippers': 0.6111111111111112,
 'Utah Jazz': 0.3333333333333333,
 'Chicago Bulls': 0.4166666666666667,
 'Miami Heat': 0.45454545454545453,
 'Atlanta Hawks': 0.5625,
 'Minnesota Timberwolves': 0.4375}

In [ ]:

# Create DataFrames for win rates
local_win_rates_df = pd.DataFrame({'Team': list(local_win_rates.keys()), 'Local Win Rate': list(local_win_rates.values())})
visitor_win_rates_df = pd.DataFrame({'Team': list(visitor_win_rates.keys()), 'Visitor Win Rate': list(visitor_win_rates.values())})

# Display the win rate DataFrames
print("Local Win Rates:")
print(local_win_rates_df)
print("\nVisitor Win Rates:")
print(visitor_win_rates_df)

In [79]:
# Parse the string into a datetime object
df['Date'] = pd.to_datetime(df['Date'])
df

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,2015-12-01,7:00p,Washington Wizards,97,Cleveland Cavaliers,85,Box Score,NaN,20562,Quicken Loans Arena,NaN
1,2015-12-01,7:00p,Los Angeles Lakers,91,Philadelphia 76ers,103,Box Score,NaN,20510,Wells Fargo Center,NaN
2,2015-12-01,7:30p,Phoenix Suns,91,Brooklyn Nets,94,Box Score,NaN,12787,Barclays Center,NaN
3,2015-12-01,8:00p,Orlando Magic,96,Minnesota Timberwolves,93,Box Score,NaN,10694,Target Center,NaN
4,2015-12-01,8:00p,Memphis Grizzlies,113,New Orleans Pelicans,104,Box Score,NaN,16020,Smoothie King Center,NaN
...,...,...,...,...,...,...,...,...,...,...,...
33,2015-10-31,7:00p,New York Knicks,117,Washington Wizards,110,Box Score,NaN,20356,Verizon Center,NaN
34,2015-10-31,7:30p,Golden State Warriors,134,New Orleans Pelicans,120,Box Score,NaN,18406,Smoothie King Center,NaN
35,2015-10-31,8:00p,Brooklyn Nets,91,Memphis Grizzlies,101,Box Score,NaN,16013,FedEx Forum,NaN
36,2015-10-31,10:00p,Phoenix Suns,101,Portland Trail Blazers,90,Box Score,NaN,17906,Moda Center,NaN
37,2015-10-31,10:30p,Sacramento Kings,109,Los Angeles Clippers,114,Box Score,NaN,19060,STAPLES Center,NaN